FROM nginx:latest



COPY ./prod/nginx.conf /etc/nginx/nginx.conf
COPY ./prod/server.conf /etc/nginx/conf.d/server.conf
COPY ./prod/maintenance.html /var/www/html/maintenance.html




CMD ["nginx", "-g", "daemon off;"]