FROM nginx:latest



COPY ./dev/nginx.conf /etc/nginx/nginx.conf
COPY ./dev/server.conf /etc/nginx/conf.d/server.conf
#distフォルダの配信　実験用
COPY ./fridge-system-prod/dist /var/www/dist



CMD ["nginx", "-g", "daemon off;"]